In [1]:
import pandas as pd

df = pd.read_csv("../dataset/tempe_cleaneddata.csv", sep="\t")
df.head(5)

,incidentid,severity,age,total_injuries,alcohol,hour_morning,hour_afternoon,hour_night,hour_latenight,nonintersection,...,cause_yield,cause_unsafe,cause_signal,cause_following,cause_distraction,cause_turn,acc_rearend,acc_leftturn,acc_sides,acc_angle
0,2584487,0,0,0,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
1,2584442,2,26,3,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,2589844,0,19,0,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
3,2579417,0,43,0,0,1,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
4,2584480,0,34,0,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0

In [4]:
out = df.describe()
pd.options.display.max_rows = len(df.columns)
out.loc[["mean", "std"]].transpose().round(3)

                             mean         std
incidentid            3120450.673  321513.903
severity                    0.456       0.764
age                        30.234      18.150
total_injuries              0.441       0.795
alcohol                     0.044       0.205
hour_morning                0.257       0.437
hour_afternoon              0.471       0.499
hour_night                  0.215       0.411
hour_latenight              0.057       0.231
nonintersection             0.429       0.495
light_daylight              0.719       0.449
light_darklighted           0.222       0.415
light_darknotlighted        0.007       0.081
light_dawndusk              0.041       0.198
meteo_cloudy                0.054       0.225
meteo_rain                  0.023       0.151
surf_wet                    0.032       0.175
type_cyclist                0.022       0.148
type_pedestrian             0.007       0.085
type_driverless             0.001       0.029
action_turn                 0.306       0.461
action_lanes                0.077       0.266
action_straight             0.493       0.500
action_slowing              0.029       0.167
cause_speeding              0.312       0.463
cause_yield                 0.199       0.399
cause_unsafe                0.078       0.269
cause_signal                0.066       0.248
cause_following             0.066       0.248
cause_distraction           0.039       0.193
cause_turn                  0.042       0.200
acc_rearend                 0.377       0.485
acc_leftturn                0.190       0.392
acc_sides                   0.131       0.337
acc_angle                   0.164       0.370